name: Test All Students

on: [push, pull_request]

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run student tests
        run: python3 test_all_students.py
