name: Test and Record Results

on: [push, pull_request]

permissions:
  contents: write

jobs:
  test-and-grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run grading script
        run: python3 test_all_students.py

      - name: Commit CSV result
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add grading_results.csv
          git commit -m "Auto-grading result [CI/CD]" || echo "No changes to commit"
          git push
